[project]
name = "florentine-abbot"
dynamic = ["version"]
description = "A suite of tools for archival scanning and digital workflow automation."
authors = [
    { name="Andrey Nalivayev", email="nalivayev@gmail.com" }
]
keywords = ["vuescan", "scanning", "automation", "archiving", "exif", "metadata"]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "watchdog>=3.0.0",
    "sqlalchemy>=2.0.0"
]

[project.scripts]
scan-batcher = "scan_batcher.cli:main"
archive-keeper = "archive_keeper.cli:main"
archive-organizer = "file_organizer.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "scan_batcher",
    "scan_batcher.workflows",
    "scan_batcher.workflows.vuescan",
    "file_organizer",
    "archive_keeper",
    "common"
]

[tool.setuptools.package-data]
"scan_batcher.workflows.vuescan" = ["*.ini"]
"file_organizer" = ["*.json"]

[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"
